# Generated by Django 2.1.3 on 2018-12-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('position', models.CharField(blank=True, max_length=32, null=True)),
                ('salary', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(blank=True, default='image/images.jpg', null=True, upload_to='image/')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.GeneralR')),
            ],
        ),
    ]
