# Generated by Django 2.1.3 on 2018-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalr',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
